# -*- coding: utf-8 -*-
"""Avore_Decisao_covid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156JRLTNsqgVMKvZArVIBRy8e4gScbYcn
"""

import numpy as np
import itertools
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from io import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from IPython.display import Image

!pip install wget
!wget https://raw.githubusercontent.com/diogocortiz/Crash-Course-IA/master/ArvoreDecis%C3%A3o/dataset_einstein.csv

df = pd.read_csv('dataset_einstein.csv', delimiter=';')

print(df.head(5))

count_row = df.shape[0]
count_col = df.shape[1]

print(count_row)
print(count_col)

# REMOVENDO OS REGISTROS NOS QUAIS PELO MENOS UM CAMPO ESTÁ EM BRANCO (NAN)
df = df.dropna()
print(df.head(5))

print('Quantidade de campos(colunas): ', df.shape[1])
print('Total de registros: ', df.shape[0])

# VAMOS VERIFICAR SE O BANCO DE DADOS ESTÁ BALANCEADO OU DESBALANCEADO
print('Total de registros negativos: ', df[df['SARS-Cov-2 exam result'] == 'negative'].shape[0])
print('Total de registros positivos: ', df[df['SARS-Cov-2 exam result'] == 'positive'].shape[0])

# VAMOS JOGAR AS ETIQUETAS PARA Y
Y = df['SARS-Cov-2 exam result'].values
print(Y)

# X SERÁ NOSSA MATRIZ COM AS FEATURES
# VAMOS PEGAR OS CAAMPOS DE TREINAMENTO (Hemoglobin, Leukocytes, Basophils, Proteina C reativa mg/dL)
X = df[['Hemoglobin', 'Leukocytes', 'Basophils', 'Proteina C reativa mg/dL']].values

# VAMOS MOSTRAR X
print(X)

x_treino, X_teste, Y_treino, Y_teste = train_test_split(X, Y, test_size=0.2, random_state=3)

# CRIAR UM ALGORITMO QUE SERÁ DO TIPO DE ÁRVORE DE DECISÃO
algoritimo_arvore = DecisionTreeClassifier(criterion='entropy', max_depth=5)

#AGORA EM MINHA_ARVORE EU TENHO ASSOCIADA A ELA O ALGORITMO DE TREINAMENTO,
# BASICAMENTE A RECEITA QUE VIMOS NA PARTE TEORICA

# AGORA PRECISAMOS TREINÁ-LAS
modelo = algoritimo_arvore.fit(x_treino, Y_treino)

print(modelo.feature_importances_)

nome_features = ['Hemoglobin', 'Leukocytes', 'Basophils', 'Proteina C reativa mg/dL']
nome_classes = modelo.classes_

dot_data = StringIO()

export_graphviz(modelo, out_file=dot_data, filled=True, feature_names=nome_features, class_names=nome_classes, rounded=True, special_characters=True)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())
graph.write_png("arvore.png")
Image('arvore.png')

importances = modelo.feature_importances_
indices = np.argsort(importances)[::-1]
print("Feature ranking: ")

for f in range(X.shape[1]):
  print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))
f, ax = plt.subplots(figsize=(11, 9))
plt.title("Feature ranking", fontsize = 20)
plt.bar(range(X.shape[1]), importances[indices], color="b", align="center")
plt.xticks(range(X.shape[1]))
plt.xlim([-1, X.shape[1]])
plt.ylabel("importance", fontsize = 18)
plt.xlabel("Index of the feature", fontsize = 18)
plt.show()

# INDICE DAS FEATURES
# 0 - 'Hemoglobin'
# 1 - 'Leukocytes'
# 2 - 'Basophils'
# 3 - 'Proteina C reativa mg/dL'

y_PREDICOES = modelo.predict(X_teste)

print('Acuracia da arvore', accuracy_score(Y_teste, y_PREDICOES))
print(classification_report(Y_teste, y_PREDICOES))